version: "3.8"
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi  # Dockerfile for FastAPI container
    ports:
      - "8000:8000"  # Expose FastAPI on port 8000
    depends_on:
      - ffmpeg
    volumes:
      - ./output_images:/app/output_images
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app  # Share the app directory between containers

  ffmpeg:
    build:
      context: .
      dockerfile: Dockerfile.ffmpeg  # Dockerfile for FFmpeg container
    expose:
      - "5000"  # FFmpeg container doesn't need to expose ports externally
    volumes:
      - ./output_images:/app/output_images
      - .:/app  # Share the app directory between containers
